// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAUepe1-KRjy4WJmi9OFfUPk3FOZ_VW5c',
    appId: '1:553902881696:web:5a522277a35637770402c5',
    messagingSenderId: '553902881696',
    projectId: 'e-sera-23e9f',
    authDomain: 'e-sera-23e9f.firebaseapp.com',
    storageBucket: 'e-sera-23e9f.firebasestorage.app',
    measurementId: 'G-LN1LWLDGR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxhvSm4eLu7pJruXM8LATAE1cuDJ_3KOI',
    appId: '1:553902881696:android:eeac59c8aa470ed80402c5',
    messagingSenderId: '553902881696',
    projectId: 'e-sera-23e9f',
    storageBucket: 'e-sera-23e9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5xEFAdwUbe39KaPHQSEKfabDEToeOG-U',
    appId: '1:553902881696:ios:1994afc2638d94320402c5',
    messagingSenderId: '553902881696',
    projectId: 'e-sera-23e9f',
    storageBucket: 'e-sera-23e9f.firebasestorage.app',
    iosBundleId: 'com.example.eSera',
  );
}
